name: 'push-remote'

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # 3.0.2
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@75d5778cddb9b18f4da47b5e4a826cd148dde62a
      with:
        args: 'https://gitlab.com/${{ secrets.GITLAB_PROJECT_ID }}'
      env:
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: ${{ secrets.GITLAB_HOSTNAME }}
        GITLAB_USERNAME: ${{ secrets.GITLAB_USERNAME }}
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_ID }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        